### PR TITLE
Fingerprint from get param with fallback to hash

### PR DESCRIPTION
**Pull request by scotthasbrouck**
@dmitrig01 grabs r from url. Preference to get param ?r=, then falls back to #r:, or returns undefined.

### CODE REVIEW

**Comment by dmitrig01** [comment]
oh sweet - I was thinking that we would just put this in the sdk v2, but i guess there's no reason not to do that. I'd like to name the new parameter something more descriptive. Maybe `branch_id`? But perhaps that's prone to collision. Any other ideas?

**Comment by scotthasbrouck** [comment]
Yeah, it was so simple, I figured I would just do it here in case we needed/wanted it. Agreed, a more descriptive parame name makes more sense. I have a break in a few hours for the rest of the afternoon, I'll give it some thought then

**Comment by scotthasbrouck** [comment]
Oh question, any reason to keep the hash as just 'r'? Perhaps we can make that more descriptive, also.

**Comment by dmitrig01** [comment]
i think we need to keep that for backward-compatibility

**Comment by dmitrig01** [comment]
gonna close this, i think that's ok. we could do it against a legacy branch, but hopefully we can phase out 0.x soon enough

**Pull request closed without merging**
