### PR TITLE
Banner bottom option

### PR DESCRIPTION
**Pull request by scotthasbrouck**
Per request form bible.com

### CODE REVIEW

**Comment by scotthasbrouck** [comment]
@dmitrig01 another feature request for bible.com

**Comment by dmitrig01** [comment]
do you want to do showOnBottom or do a position: top | bottom (or others later)?

also can you add to changelog and remove the merge conflcits?

**Comment by scotthasbrouck** [comment]
Oh, good call. I like positon:top | bottom, with a default to top.

**Comment by scotthasbrouck** [comment]
@dmitrig01 merge conflicts fixed, changelog updated, and changed to position:top|bottom

**Comment by dmitrig01** [comment]
:+1:

**Pull request merged**
