### PR TITLE
Two overhauls

### PR DESCRIPTION
**Pull request by dmitrig01**
- redid the banner completely - split resources into multiple files, make it much simpler (this needs a little more work - animations not quite working etc)
- turned on much stricture Closure Compiler type checking, and fixed a ton of type errors

### CODE REVIEW

**Comment by dmitrig01** [comment]
@scotthasbrouck

**Comment by scotthasbrouck** [comment]
:+1:  Looks good

**Comment by kenleezle** [comment]
@dmitrig01 will this be pushed to bower today?

**Comment by dmitrig01** [comment]
yup

**Comment by kenleezle** [comment]
:+1:

**Pull request merged**
