### PR TITLE
Cordova fix

### PR DESCRIPTION
**Pull request by scotthasbrouck**
Things in this PR:
1. Fix that failed to call Cordova specific open on subsequent launches
2. Fix that moved the close endpoint in resources from web sdk to cordova sdk
3. Refactors cordova testbed app
4. Adds cordova integration tests
5. Fixes unit tests for cordova

### CODE REVIEW

**Comment by scotthasbrouck** [comment]
@wedgybo here's the fix for the close() method. I still need to take a look at your branch and merge in your fixes to storage. I'll do that first thing tomorrow, then we can see if this is ready to go!

**Comment by dmitrig01** [comment]
nice!!

**Comment by scotthasbrouck** [comment]
@dmitrig01 feel free to take a look at this. I think I've used Sauce too much today for their liking - everything just times out after the first 50~ vms are spun up and pass. I honestly don't know what's going on, and I need to get back to splash. But all tests do in fact pass on this.

**Comment by dmitrig01** [comment]
:+1:

**Pull request merged**
