### PR TITLE
Saucelabs + CircleCI

### PR DESCRIPTION
**Pull request by scotthasbrouck**
Saucelabs testing in 33 browser configs. If we do many more than this, testing is going to get slow. We're covering every major browser, so the only other tests we could really be doing is the same browser on multiple operating systems. I don't think that's necessary.

### CODE REVIEW

**Comment by scotthasbrouck** [comment]
@dmitrig01 this is ready to go, but integration tests are commented out. Your call if you want to merge this now, or if I should finish that up first.

**Comment by scotthasbrouck** [comment]
@dmitrig01 got integration working with sauce! Found a stupid mistake stopping it from working with Phantom, so then it worked in sauce.

**Comment by scotthasbrouck** [comment]
So this is all tests, running in sauce now.

**Comment by dmitrig01** [comment]
awesome!!!! :+1:

**Pull request merged**
