### PR TITLE
Fixes issue with Cordova SDK not loading previous session

### PR DESCRIPTION
**Pull request by scotthasbrouck**
Simple fix for Cordova and Titanium. They should not be calling *just* finishInit if a previous session is present.

Addresses issue #78

### CODE REVIEW

**Comment by dmitrig01** [comment]
good catch

**Comment by scotthasbrouck** [comment]
Credit goes to: @wedgybo

**Comment by wedgybo** [comment]
Thanks guys I'll check this out and see if it fixes my issue!

Some more information though. I think the issue is actually with the close statement being called on pause.

It's being added to the queue but in my case it's never actually executed. I've not quite worked out how the queue operates yet. But my guess is close() needs to jump to the front of the queue, or the queue needs cleared before it's added as it looks like it runs next() once then exits.

I think the correct fix is to make sure close() is actually executed as this will clear out the session id and that check would fail as expected.

Just my thoughts! I'll report back shortly with an updated on how this PR works for me!

**Comment by wedgybo** [comment]
I'm afraid it wasn't enough so I got stuck in properly. I've raised PR #80 to have a discussion about it.

**Comment by aaustin** [comment]
so can we merge this one?

**Comment by wedgybo** [comment]
I don't think it will hurt, but it doesn't fix the issue I was reporting.

Happy 'Merica day guys! Enjoy your holiday. We're having a mini celebration with you here in rainy Scotland :us: :gb: We can sort out the proper fixes next week!

**Comment by scotthasbrouck** [comment]
hey @wedgybo thanks for the happy 'Merica day wishes haha
I found the root cause to the 2nd issue over the weekend. All of our API endpoints are stored in src/1_resources.js. Some of the endpoints are used either by only the web SDK, or only the Cordova SDK. The end point for the close method somehow ended up in the Web SDK block, moving it to the Cordova block fixed the issue. I did a lot of cleanup in the testbed app for future engineers wanting to work with Cordova, and wrote a suite of integration tests for Cordova - previously there were no tests. So moving forward this should help prevent obvious bugs like this!
This branch was misspelled and it annoyed me :) So I finished this fix on a new branch called cordova_fix, which I'll make a PR for.

**Pull request closed without merging**
