### PR TITLE
Super stupid IE11 XHR bug fix

### PR DESCRIPTION
**Pull request by scotthasbrouck**
IE11 can't handle setting the timeout of an XHRRequest prior to calling open()

### CODE REVIEW

**Comment by scotthasbrouck** [comment]
@dmitrig01 super simple one line change to fix a live bug with IE11

**Comment by dmitrig01** [comment]
that's dumb

**Comment by dmitrig01** [comment]
you wanna do a point release?

**Comment by scotthasbrouck** [comment]
yeah 1.5.1

**Pull request merged**
